name: Godot Docker Image CI

on: [push]

jobs:

  build:
    name: Godot Game Engine Headless Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag Godot-CI-CD:$(date +%d-%b-%y)
